[Log]
Level = "debug"
Outputs = [ "stdout",]

[SyncDB]
Database = "postgres"
User = "test_user"
Password = "test_password"
Name = "test_db"
Host = "zkevm-bridge-db"
Port = "5432"
MaxConns = 20

[ClaimTxManager]
Enabled = true
FrequencyToMonitorTxs = "1s"
RetryInterval = "1s"
RetryNumber = 10

[Etherman]
L1URL = "http://zkevm-mock-l1-network:8545"
L2URLs = [ "http://zkevm-json-rpc:8123",]

[Synchronizer]
SyncInterval = "1s"
SyncChunkSize = 100

[BridgeController]
Store = "postgres"
Height = 32

[BridgeServer]
GRPCPort = "9090"
HTTPPort = "8080"
CacheSize = 100000
DefaultPageLimit = 25
MaxPageLimit = 100
BridgeVersion = "v1"

[NetworkConfig]
GenBlockNumber = 1
PolygonBridgeAddress = "0x5F1A59e5Ad3faf570961c717b6AFA08abb5006B1"
PolygonZkEVMGlobalExitRootAddress = "0x5F1A59e5Ad3faf570961c717b6AFA08abb5006B1"
L2PolygonBridgeAddresses = [ "0x5F1A59e5Ad3faf570961c717b6AFA08abb5006B1",]

[ClaimTxManager.PrivateKey]
Path = "/pk/keystore.claimtxmanager"
Password = "testonly"

[BridgeServer.DB]
Database = "postgres"
User = "test_user"
Password = "test_password"
Name = "test_db"
Host = "zkevm-bridge-db"
Port = "5432"
MaxConns = 20
